BEGIN
DBMS_OUTPUT.PUT_LINE('EXEMPLO 1');
END;
/

BEGIN
DBMS_OUTPUT.PUT_LINE('EXEMPLO 2'|| ' ' ||'EXEMPLO3');
DBMS_OUTPUT.PUT_LINE('EXEMPLO 2'|| CHR(9) ||'EXEMPLO3');
DBMS_OUTPUT.PUT_LINE('EXEMPLO 2'|| CHR(10) ||'EXEMPLO3');
DBMS_OUTPUT.PUT_LINE('EXEMPLO 2'|| CHR(13) ||'EXEMPLO3');
END;
/

BEGIN
DBMS_OUTPUT.PUT_LINE('EXEMPLO 2'|| ' ' ||'EXEMPLO3');
-- TABULAÇÃO
DBMS_OUTPUT.PUT_LINE('EXEMPLO 2'|| CHR(9) ||'EXEMPLO3');
-- NOVA LINHA
DBMS_OUTPUT.PUT_LINE('EXEMPLO 2'|| CHR(10) ||'EXEMPLO3');
-- NOVA LINHA (RETORNO DO CARRO)
DBMS_OUTPUT.PUT_LINE('EXEMPLO 2'|| CHR(13) ||'EXEMPLO3');
END;
/

SET SERVEROUT ON
DECLARE
V_EMP_ID NUMBER(5);
V_COMM_PCT NUMBER(2) := 1;
V_COUNT NUMBER(2) NOT NULL := 1;
V_DATE DATE := SYSDATE+1;
C_TAX CONSTANT NUMBER(5) := 23;
BEGIN
DBMS_OUTPUT.PUT_LINE('Employee ID: '||V_EMP_ID);
DBMS_OUTPUT.PUT_LINE('Comissão: '||V_COMM_PCT);
V_COUNT := V_COUNT + 1;
DBMS_OUTPUT.PUT_LINE('Count: '|| V_COUNT );
V_COUNT := 30;
DBMS_OUTPUT.PUT_LINE('DATE: '||TO_CHAR(V_DATE,'DD/MM/RRRR HH24:MI:SS'));
END;
/

DECLARE
V_LAST_NAME VARCHAR(25):='Xiuderico';
V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
DBMS_OUTPUT.PUT_LINE(V_LAST_NAME);

END;
/