SET SERVEROUT ON
DECLARE
    REG_REGIONS REGIONS%ROWTYPE;
    CURSOR CUR_REGIONS IS
    SELECT REGION_ID,REGION_NAME
    FROM REGIONS;
    BEGIN
    OPEN CUR_REGIONS;
    LOOP
    FETCH CUR_REGIONS INTO REG_REGIONS;
    EXIT WHEN CUR_REGIONS%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(REG_REGIONS.REGION_ID || ' '||
    REG_REGIONS.REGION_NAME);
    END LOOP;
    CLOSE CUR_REGIONS;
END;
/