-- some duas colunas da tabela salesOrderDetail


--****** RESULTADOS NO DATE.SQL *******
-- COMO PEGAR A DATA ATUAL E CONCATENAR COM A PALAVRA 'LIMAO'
-- PEGAR O TIMESTAMP EM SELECT
-- PEGAR NA TABELA PERSON AS MODIFICACOES ENTRE 2014 E HOJE
-- PEGAR SOMENTE O ANO ATUAL
-- PEGAR SOMENTE O MES ATUAL
--****** RESULTADOS NO DATE.SQL *******