SET SERVEROUT ON
    DECLARE
        V_REGION_ID REGIONS.REGION_ID%TYPE;
        V_REGION_NAME REGIONS.REGION_NAME%TYPE;
    
    CURSOR CUR_REGIONS IS
    SELECT REGION_ID,REGION_NAME
    FROM REGIONS;
    BEGIN
    OPEN CUR_REGIONS;
    LOOP
    FETCH CUR_REGIONS INTO V_REGION_ID,V_REGION_NAME;
    EXIT WHEN CUR_REGIONS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_REGION_ID || ' '|| V_REGION_NAME);
    END LOOP;
    CLOSE CUR_REGIONS;
END;
/

SET SERVEROUT ON
BEGIN
FOR REG_CUR IN (SELECT * FROM REGIONS) LOOP
DBMS_OUTPUT.PUT_LINE(REG_CUR.REGION_ID || ' '||
REG_CUR.REGION_NAME);
END LOOP;
END;
/

SET SERVEROUT ON
    DECLARE
        REG_REGIONS REGIONS%ROWTYPE;
    CURSOR CUR_REGIONS IS
        SELECT REGION_ID,REGION_NAME
        FROM REGIONS;
    BEGIN
    OPEN CUR_REGIONS;
    FETCH CUR_REGIONS INTO REG_REGIONS;
    WHILE CUR_REGIONS%FOUND LOOP
    DBMS_OUTPUT.PUT_LINE(REG_REGIONS.REGION_ID || ' '||
    REG_REGIONS.REGION_NAME);
    FETCH CUR_REGIONS INTO REG_REGIONS;
    END LOOP;
    CLOSE CUR_REGIONS;
    END;
/